server:
  port: 8080
  secret: 'VANA_BOARD'
  cors_whitelist:
  -
  -
  -

mongodb:
  url: mongodb://username:password@localhost:27017/my-database

redis:
  host: 127.0.0.1
  port: 6379
  #
  # server:
  #   port: 8080
  #   cors_whitelist:
  #   -
  #   -
  #   -
  #
  # mongodb:
  #   url: mongodb://49.247.204.250:27017/vana-board
  #
  # redis:
  #   host: 49.247.204.250
  #   port: 6379
